### PR TITLE
Ambr 983

### PR DESCRIPTION
**Pull request by mcbrandt13**
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-983

*Related PRs:* 
> None.

## What this PR does:

>Updating mobile to use mailto for sharing an article via email. I deleted the EmailArticleController. However, it appears that the model is being used for a Feedback feature? There are a still .ftl files for emailArticleBody,emailSuccess, etc., but I don't know for sure if those are being used for the Feedback feature or not. 

## Developer Notes

> Unsure if there are more files I can remove.

# Code Author Tasks:

> This list should be finished before code review:
- [ ] Ticket AC is updated with any decisions made in comments or side conversations.
- [ ] Testing or PO Accept notes that will assist the tester, Product Owner or reviewer are set in the ticket.
- [ ] All PRs are created and linked for work I have done against other projects as part of this ticket.
- [ ] Intergration Tests have been addressed.  QA has been notified of the feature and a ticket has been created for that work, or integration tests have been updated. 
- [ ] There are unit tests sufficient for both positive and negative test cases, test coverage has not decreased as part of this work. 
- [ ] Any necessary documentation in confluence or READMEs is updated.

If I used outside libraries:
- [ ] Confirmed unique - we aren't using something similar elsewhere
- [ ] License comports with our licensing (MIT preferable)

If I modified any environment variables:
- [ ] Pull requests are created to change the files in molten or in SALT-formulas.

If I made any database changes:
- [ ] DB migration scripts are created and this detail is added to testing notes in the ticket.

# Code Reviewer Tasks
- [x] I read through the JIRA ticket's AC before doing the rest of the review.
- [x] I ran the code (in the review environment or locally). I agree the running code fulfills the Acceptance Criteria as stated on the JIRA ticket. If not practical I have seen some evidence that the code does what it says (tests have passed).

### CODE REVIEW

**Comment by egh** [comment]
image
Looks good

**Comment by egh** [comment]
There are some more things you could delete, I think:
```
src/main/webapp/WEB-INF/themes/desktop/ftl/article/email.ftl
src/main/webapp/WEB-INF/themes/mobile/ftl/article/email.ftl
src/main/webapp/WEB-INF/themes/root/ftl/article/emailArticleBody.ftl
```
as well as modifications to `src/main/webapp/WEB-INF/themes/root/config/email.yaml` and `src/main/webapp/WEB-INF/themes/mobile/resource/css/feedback.css` to remove old config/styles that are no longer needed.

**Comment by mcbrandt13** [comment]
Removed those other files and cleaned up feedback.css. Looks like the teamcity jobs for the tests all passed.

**Comment by egh** [comment]
do we still need ./src/main/webapp/WEB-INF/themes/desktop/ftl/article/emailSuccess.ftl and  ./src/main/webapp/WEB-INF/themes/root/ftl/article/emailSuccessBody.ftl? I don't see them used anymore.

**Comment by mcbrandt13** [comment]
I think those are still used in the feedback feature? It looked like the form was used for feedback and share, so maybe when the ticket for removing feedback is done these will be removed then?

**Comment by egh** [comment]
They all have `article` in the path and when I search the file names in the repo I don't see them referenced anywhere. But I could be wrong, maybe they are still being used.

**Comment by mcbrandt13** [comment]
Removed those, and tests in teamcity seemed to have passed.

**Comment by egh** [comment]
Looks good, there is still 

src/main/webapp/WEB-INF/themes/mobile/ftl/article/emailSuccess.ftl

and some config for `emailThisArticle` in src/main/webapp/WEB-INF/themes/root/config/email.yaml

**Comment by mcbrandt13** [comment]
Should I delete that .yaml file entirely?

**Comment by egh** [comment]
no it looks like it is used by the feedback feature.

**Comment by egh** [comment]
Thanks @mcbrandt13 looks good! Just waiting for the tests to pass before merging.

**Pull request merged**
