### PR TITLE
AMBR-218 Upgrade maven tomcat plugin to 7

### PR DESCRIPTION
**Pull request by egh**
*JIRA issue:* https://jira.plos.org/jira/browse/AMBR-218

*Related PRs:* 

None.

## What this PR does:

Upgrade to maven tomcat plugin 7 for local development purposes. This brings us in line with the version of tomcat we use in production.

This will have no effect on QA/testing or production.

# Code Author Tasks:

> This list should be finished before code review:
- [x] Ticket AC is updated with any decisions made in comments or side conversations.
- [x] Testing or PO Accept notes that will assist the tester, Product Owner or reviewer are set in the ticket.
- [x] All PRs are created and linked for work I have done against other projects as part of this ticket.
- [x] Intergration Tests have been addressed.  QA has been notified of the feature and a ticket has been created for that work, or integration tests have been updated. 
- [x] There are unit tests sufficient for both positive and negative test cases, test coverage has not decreased as part of this work. 
- [x] Any necessary documentation in confluence or READMEs is updated.

# Code Reviewer Tasks
- [x] I read through the JIRA ticket's AC before doing the rest of the review.
- [x] I ran the code (in the review environment or locally). I agree the running code fulfills the Acceptance Criteria as stated on the JIRA ticket. If not practical I have seen some evidence that the code does what it says (tests have passed).
- [ ] The code adheres to the values and guidelines of the project. (link here)
- [ ] Security vulnerabilities have been addressed.

### CODE REVIEW

**Comment by egh** [comment]
For sure, thanks Shawn!!

**Comment by egh** [comment]
@sgatchell to be thorough, can you delete or check the final checkboxes, or tell me what to do to address any issues?

**Comment by sgatchell** [comment]
You'd need to provide a link to the project guidelines, or otherwise assure me that they are met and that any security issues have been addressed.  I will then rubber stamp your assurances by checking some boxes.

**Comment by sgatchell** [comment]
Or, I'll delete the boxes because they are vague and burdensome.

**Pull request merged**
